# Generated by Django 3.1 on 2020-08-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qari',
            name='syllabus',
        ),
        migrations.AddField(
            model_name='qari',
            name='day1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='qari',
            name='day2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='qari',
            name='day3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='qari',
            name='day4',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='qari',
            name='day5',
            field=models.TextField(default=''),
        ),
    ]
